# Site A configuration from line 3 to line 26

config setup
    charondebug="all"
    uniqueids=yes

conn site-a-to-b
    type=tunnel
    auto=start
    keyexchange=ikev2

    # My side (Site A - Ubuntu)
    left=10.0.2.15
    leftid=10.0.2.15
    leftsubnet=192.168.10.0/24

    # Remote side (Site B - Kali)
    right=10.0.2.16
    rightid=10.0.2.16
    rightsubnet=192.168.20.0/24

    authby=secret

    # Cipher suites
    ike=aes256-sha1-modp1024!
    esp=aes256-sha1!

  # Site B configuration from line 30 to line 53

  config setup
    charondebug="all"
    uniqueids=yes

conn site-b-to-a
    type=tunnel
    auto=start
    keyexchange=ikev2

    # My side (Site B - Kali)
    left=10.0.2.16
    leftid=10.0.2.16
    leftsubnet=192.168.20.0/24

    # Remote side (Site A - Ubuntu)
    right=10.0.2.15
    rightid=10.0.2.15
    rightsubnet=192.168.10.0/24

    authby=secret

    # Cipher suites
    ike=aes256-sha1-modp1024!
    esp=aes256-sha1!
